# Generated by Django 5.0.2 on 2025-05-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
