# Generated by Django 5.2.1 on 2025-05-25 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_squads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squadmember',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squads.squad'),
        ),
        migrations.AddField(
            model_name='squadmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='members',
            field=models.ManyToManyField(related_name='squads', through='squads.SquadMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='squadmember',
            unique_together={('squad', 'user')},
        ),
    ]
