# Generated by Django 5.0.2 on 2025-05-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squad',
            name='max_members',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
